#include <stdio.h>
#include <stdlib.h>

int main() 
{
   int _aAAAAAAAAAAAAAAAA, _aAAAAAAAAAAAAAAA2, _bBBBBBBBBBBBBBBBB, _xXXXXXXXXXXXXXXXX, _cCCCCCCCCCCCCCCC1, _cCCCCCCCCCCCCCCC2;
   printf("Enter _aAAAAAAAAAAAAAAAA:");
   scanf("%d", &_aAAAAAAAAAAAAAAAA);
   printf("Enter _bBBBBBBBBBBBBBBBB:");
   scanf("%d", &_bBBBBBBBBBBBBBBBB);
   for (int _aAAAAAAAAAAAAAAA2 = _aAAAAAAAAAAAAAAAA; _aAAAAAAAAAAAAAAA2 <= _bBBBBBBBBBBBBBBBB; _aAAAAAAAAAAAAAAA2++)
   printf("%d\n", _aAAAAAAAAAAAAAAA2 * _aAAAAAAAAAAAAAAA2);
   for (int _aAAAAAAAAAAAAAAA2 = _bBBBBBBBBBBBBBBBB; _aAAAAAAAAAAAAAAA2 <= _aAAAAAAAAAAAAAAAA; _aAAAAAAAAAAAAAAA2++)
   printf("%d\n", _aAAAAAAAAAAAAAAA2 * _aAAAAAAAAAAAAAAA2);
   _xXXXXXXXXXXXXXXXX = 0;
   _cCCCCCCCCCCCCCCC1 = 0;
   while (_cCCCCCCCCCCCCCCC1 < _aAAAAAAAAAAAAAAAA)
   {
   {
   _cCCCCCCCCCCCCCCC2 = 0;
   while (_cCCCCCCCCCCCCCCC2 < _bBBBBBBBBBBBBBBBB)
   {
   {
   _xXXXXXXXXXXXXXXXX = _xXXXXXXXXXXXXXXXX + 1;
   _cCCCCCCCCCCCCCCC2 = _cCCCCCCCCCCCCCCC2 + 1;
   }
   }
   _cCCCCCCCCCCCCCCC1 = _cCCCCCCCCCCCCCCC1 + 1;
   }
   }
   printf("%d\n", _xXXXXXXXXXXXXXXXX);
   _xXXXXXXXXXXXXXXXX = 0;
   _cCCCCCCCCCCCCCCC1 = 1;
   do
   {
   _cCCCCCCCCCCCCCCC2 = 1;
   do
   {
   _xXXXXXXXXXXXXXXXX = _xXXXXXXXXXXXXXXXX + 1;
   _cCCCCCCCCCCCCCCC2 = _cCCCCCCCCCCCCCCC2 + 1;
   }
   while (!(_cCCCCCCCCCCCCCCC2 > _bBBBBBBBBBBBBBBBB));
   _cCCCCCCCCCCCCCCC1 = _cCCCCCCCCCCCCCCC1 + 1;
   }
   while (!(_cCCCCCCCCCCCCCCC1 > _aAAAAAAAAAAAAAAAA));
   printf("%d\n", _xXXXXXXXXXXXXXXXX);
   system("pause");
    return 0;
}
